In [1]:
import pandas as pd

In [2]:
df =  pd.DataFrame({'columna1' : [1, 2, 3, 4], 'columna2' : ['a', 'b', 'c', 'd']})

In [3]:
df

   columna1 columna2
0         1        a
1         2        b
2         3        c
3         4        d

In [9]:
df.shape

(4, 2)

# Importar un dataframe

In [19]:
df = pd.read_csv('../data_raw/iris/iris.data', header=None)

In [24]:
df.head()

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [25]:
df.head(2)

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa

In [26]:
df.tail(2)

       0    1    2    3               4
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

In [27]:
nombres = ['longitud_sepalo', 'ancho_sepalo', 'longitud_petalo', 'ancho_petalo', 'clase']

In [28]:
nombres

['longitud_sepalo', 'ancho_sepalo', 'longitud_petalo', 'ancho_petalo', 'clase']

In [29]:
df.columns = nombres

In [30]:
df.head()

   longitud_sepalo  ancho_sepalo  longitud_petalo  ancho_petalo        clase
0              5.1           3.5              1.4           0.2  Iris-setosa
1              4.9           3.0              1.4           0.2  Iris-setosa
2              4.7           3.2              1.3           0.2  Iris-setosa
3              4.6           3.1              1.5           0.2  Iris-setosa
4              5.0           3.6              1.4           0.2  Iris-setosa

In [31]:
df.columns

Index(['longitud_sepalo', 'ancho_sepalo', 'longitud_petalo', 'ancho_petalo',
       'clase'],
      dtype='object')

In [32]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [33]:
df.shape

(150, 5)

# Resumen estadístico descriptivo

genera un resumen estadístico descriptivo de un DataFrame o Serie, calculando automáticamente métricas clave para columnas numéricas como la:
- cuenta (), 
- media (),
- desviación estándar (),
- valores mínimos/máximos y cuartiles (25%, 50%, 75%)

In [34]:
df.describe()

       longitud_sepalo  ancho_sepalo  longitud_petalo  ancho_petalo
count       150.000000    150.000000       150.000000    150.000000
mean          5.843333      3.054000         3.758667      1.198667
std           0.828066      0.433594         1.764420      0.763161
min           4.300000      2.000000         1.000000      0.100000
25%           5.100000      2.800000         1.600000      0.300000
50%           5.800000      3.000000         4.350000      1.300000
75%           6.400000      3.300000         5.100000      1.800000
max           7.900000      4.400000         6.900000      2.500000

# frecuencia de valores únicos

In [35]:
df['clase'].value_counts()

clase
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

# groupby()

longitud_sepalo

In [49]:
df.groupby('clase')['longitud_sepalo'].mean()

clase
Iris-setosa        5.006
Iris-versicolor    5.936
Iris-virginica     6.588
Name: longitud_sepalo, dtype: float64

### 🧠 Mini flujo real de un analista

Cuando un analista abre un dataset normalmente hace esto:

- df.head()
- df.info()
- df.describe()
- df["species"].value_counts()
- df.groupby("species").mean()

Esto ya da una idea completa del dataset en 30 segundos.

# Para trasponer las filas y las columnas

In [36]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
longitud_sepalo,5.1,4.9,4.7,4.6,5.0,5.4,4.6,5.0,4.4,4.9,...,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9
ancho_sepalo,3.5,3.0,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,...,3.1,3.1,2.7,3.2,3.3,3.0,2.5,3.0,3.4,3.0
longitud_petalo,1.4,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,...,5.6,5.1,5.1,5.9,5.7,5.2,5.0,5.2,5.4,5.1
ancho_petalo,0.2,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,...,2.4,2.3,1.9,2.3,2.5,2.3,1.9,2.0,2.3,1.8
clase,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,...,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica

# Para ordenar un dataframe de manera asendente o decendente

In [37]:
df.sort_values('ancho_sepalo')

,longitud_sepalo,ancho_sepalo,longitud_petalo,ancho_petalo,clase
60,5.0,2.0,3.5,1.0,Iris-versicolor
62,6.0,2.2,4.0,1.0,Iris-versicolor
119,6.0,2.2,5.0,1.5,Iris-virginica
68,6.2,2.2,4.5,1.5,Iris-versicolor
87,6.3,2.3,4.4,1.3,Iris-versicolor
...,...,...,...,...,...
5,5.4,3.9,1.7,0.4,Iris-setosa
14,5.8,4.0,1.2,0.2,Iris-setosa
32,5.2,4.1,1.5,0.1,Iris-setosa
33,5.5,4.2,1.4,0.2,Iris-setosa
15,5.7,4.4,1.5,0.4,Iris-setosa

In [38]:
df.sort_values('ancho_sepalo', ascending = False)

,longitud_sepalo,ancho_sepalo,longitud_petalo,ancho_petalo,clase
15,5.7,4.4,1.5,0.4,Iris-setosa
33,5.5,4.2,1.4,0.2,Iris-setosa
32,5.2,4.1,1.5,0.1,Iris-setosa
14,5.8,4.0,1.2,0.2,Iris-setosa
5,5.4,3.9,1.7,0.4,Iris-setosa
...,...,...,...,...,...
53,5.5,2.3,4.0,1.3,Iris-versicolor
62,6.0,2.2,4.0,1.0,Iris-versicolor
68,6.2,2.2,4.5,1.5,Iris-versicolor
119,6.0,2.2,5.0,1.5,Iris-virginica
60,5.0,2.0,3.5,1.0,Iris-versicolor

# Para seleccionar columnas del DF

In [39]:
df[['longitud_sepalo', 'longitud_petalo']]

     longitud_sepalo  longitud_petalo
0                5.1              1.4
1                4.9              1.4
2                4.7              1.3
3                4.6              1.5
4                5.0              1.4
..               ...              ...
145              6.7              5.2
146              6.3              5.0
147              6.5              5.2
148              6.2              5.4
149              5.9              5.1

[150 rows x 2 columns]

# Para seleccionar por indice del DF

In [40]:
df[:3]

   longitud_sepalo  ancho_sepalo  longitud_petalo  ancho_petalo        clase
0              5.1           3.5              1.4           0.2  Iris-setosa
1              4.9           3.0              1.4           0.2  Iris-setosa
2              4.7           3.2              1.3           0.2  Iris-setosa

# Para seleccionar por nombre

In [50]:
df.loc[0]

longitud_sepalo            5.1
ancho_sepalo               3.5
longitud_petalo            1.4
ancho_petalo               0.2
clase              Iris-setosa
Name: 0, dtype: object

# Para seleccionar por fina y columna

In [51]:
df.loc[0, 'ancho_sepalo']

np.float64(3.5)

# Para seleccionar varias columnas

In [52]:
df.loc[:, ['ancho_sepalo', 'ancho_petalo']]

     ancho_sepalo  ancho_petalo
0             3.5           0.2
1             3.0           0.2
2             3.2           0.2
3             3.1           0.2
4             3.6           0.2
..            ...           ...
145           3.0           2.3
146           2.5           1.9
147           3.0           2.0
148           3.4           2.3
149           3.0           1.8

[150 rows x 2 columns]

# Para seleccionar por indice y por columna

In [41]:
df.iloc[[4, 10], [0, 2]]

    longitud_sepalo  longitud_petalo
4               5.0              1.4
10              5.4              1.5

# Filtros para conjunto de datos

In [42]:
df[df['longitud_sepalo'] > 5]

,longitud_sepalo,ancho_sepalo,longitud_petalo,ancho_petalo,clase
0,5.1,3.5,1.4,0.2,Iris-setosa
5,5.4,3.9,1.7,0.4,Iris-setosa
10,5.4,3.7,1.5,0.2,Iris-setosa
14,5.8,4.0,1.2,0.2,Iris-setosa
15,5.7,4.4,1.5,0.4,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

In [44]:
df[(df['longitud_sepalo'] > 5) & (df['longitud_petalo'] > 1.4)]

,longitud_sepalo,ancho_sepalo,longitud_petalo,ancho_petalo,clase
5,5.4,3.9,1.7,0.4,Iris-setosa
10,5.4,3.7,1.5,0.2,Iris-setosa
15,5.7,4.4,1.5,0.4,Iris-setosa
18,5.7,3.8,1.7,0.3,Iris-setosa
19,5.1,3.8,1.5,0.3,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

# Mas filtros a tener en cuenta

### 1️⃣ Filtro por múltiples condiciones (AND)

Este es el que ya viste y es probablemente el más común.
Ejemplo: flores con sépalo mayor a 5 y pétalo mayor a 3.

- df[(df["sepal_length"] > 5) & (df["petal_length"] > 3)]


Lo que suelen preguntar en entrevistas:
“Filtra las filas donde dos condiciones se cumplan al mismo tiempo.”
Variación típica:

- df[(df["age"] > 30) & (df["salary"] > 50000)]

### 2️⃣ Filtro por valores específicos (isin)

Esto es muy usado cuando quieres filtrar varias categorías.
Ejemplo con el famoso Iris Dataset:

- df[df["species"].isin(["setosa", "virginica"])]

Esto es equivalente a:

- (df["species"] == "setosa") | (df["species"] == "virginica")


pero mucho más limpio.
En entrevistas lo preguntan así:
“Filtra las filas donde la columna pertenezca a una lista de valores.”
Ejemplo real de negocio:

- df[df["country"].isin(["Colombia", "Peru", "Chile"])]

### 2️⃣ Filtro por valores específicos (isin)

Esto es muy usado cuando quieres filtrar varias categorías.
Ejemplo con el famoso Iris Dataset:

- df[df["species"].isin(["setosa", "virginica"])]

Esto es equivalente a:

- (df["species"] == "setosa") | (df["species"] == "virginica")

pero mucho más limpio.
En entrevistas lo preguntan así:
“Filtra las filas donde la columna pertenezca a una lista de valores.”
Ejemplo real de negocio:

- df[df["country"].isin(["Colombia", "Peru", "Chile"])]

### 🧠 BONUS (muy común en entrevistas)

Filtro por texto:

- df[df["name"].str.contains("Juan")]

Esto filtra todas las filas donde aparezca “Juan”.

# Operaciones entre columnas

In [45]:
df['ancho_sepalo'] - df['longitud_petalo']

0      2.1
1      1.6
2      1.9
3      1.6
4      2.2
      ...
145   -2.2
146   -2.5
147   -2.2
148   -2.0
149   -2.1
Length: 150, dtype: float64

# Para saber si hay valores null

In [46]:
df.isna()

     longitud_sepalo  ancho_sepalo  longitud_petalo  ancho_petalo  clase
0              False         False            False         False  False
1              False         False            False         False  False
2              False         False            False         False  False
3              False         False            False         False  False
4              False         False            False         False  False
..               ...           ...              ...           ...    ...
145            False         False            False         False  False
146            False         False            False         False  False
147            False         False            False         False  False
148            False         False            False         False  False
149            False         False            False         False  False

[150 rows x 5 columns]

In [47]:
df.isna().sum()

longitud_sepalo    0
ancho_sepalo       0
longitud_petalo    0
ancho_petalo       0
clase              0
dtype: int64

In [48]:
df.isna().sum().sum()

np.int64(0)